site_name: freezer manager
pages:
- Home: index.md
- About: about.md
- API: api.md
- Requests:
  - check_token: requests/check_token.md
  - types: requests/types.md
  - freezer: requests/freezers.md
  - freezer_next_id: requests/freezer_next_id.md
theme:
  name: 'material'
